import React from "react";
import { useState } from "react";
import Modal from "../components/Modal";
import GalleryItem from "../components/GalleryItem";

export default function Gallery() {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [imgUrl, setImgUrl] = useState(null);

  const [toggleMenu, setToggleMenu] = useState(true);

  return (
    <>
      <Modal
        className="modal"
        isModalOpen={isModalOpen}
        setIsModalOpen={setIsModalOpen}
        imgUrl={imgUrl}
      />
      <div className="header">
        <nav className="top-nav">
          <a
            href="https://dragonogs.github.io/photography/"
            className="nav-brand"
          >
            <span>Oliver </span>
            <span>Shipley.</span>
          </a>
          <button
            onClick={() => setToggleMenu((prev) => !prev)}
            className="dropdown-btn"
          >
            <i className="fa-solid fa-bars"></i>
          </button>
        </nav>
        <ul
          className={`dropdown-menu`}
          style={{ display: toggleMenu ? "none" : "block" }}
        >
          <li>
            <a
              href="https://dragonogs.github.io/photography/"
              className="nav-link-active"
            >
              Gallery
            </a>
          </li>
          <li>
            <a
              href="https://dragonogs.github.io/photography/about"
              className="nav-link"
            >
              About
            </a>
          </li>
          <li>
            <a
              href="https://dragonogs.github.io/photography/contact"
              className="nav-link"
            >
              Contact
            </a>
          </li>
        </ul>
      </div>
      <main className="main-content">
        <nav className="main-nav">
          <ul className="nav-menu">
            <li>
              <a
                href="https://dragonogs.github.io/photography/"
                className="nav-link-active serif"
              >
                Gallery
              </a>
            </li>
            <li>
              <a
                href="https://dragonogs.github.io/photography/about"
                className="nav-link serif"
              >
                About
              </a>
            </li>
            <li>
              <a
                href="https://dragonogs.github.io/photography/contact"
                className="nav-link serif"
              >
                Contact
              </a>
            </li>
          </ul>
        </nav>
        <div className="gallery-grid">
          <GalleryItem
            url="photos/DSC05930-Enhanced-NR.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC01108.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC04960.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />

          <GalleryItem
            url="photos/DSC05942.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />

          <GalleryItem
            url="photos/DSC03997.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC06176.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC04354.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC06324.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC05082.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />

          <GalleryItem
            url="photos/DSC04322.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC04365.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC06023.webp "
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSCF7201.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC06067.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />

          <GalleryItem
            url="photos/DSC00894.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC03509.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />

          <GalleryItem
            url="photos/DSC04945.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC01732.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC07619.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/image0.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC07688.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />

          <GalleryItem
            url="photos/DSC07153.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />

          <GalleryItem
            url="photos/DSC07358.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC07705.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />

          <GalleryItem
            url="photos/DSC07906.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC08050.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC08140.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />

          <GalleryItem
            url="photos/DSC02628.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC02483.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC00592-Enhanced-NR.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC02544.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC02643.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC02523.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC01134.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC00936.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC01017.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC02321.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />

          <GalleryItem
            url="photos/DSC00808.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC01005.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC00994.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC00230.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC01102.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC00872.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC03704.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC00941.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC00947.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC01613.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC03810.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC03814.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC02241.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC03834.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC03724.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC00861.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC01231.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
          <GalleryItem
            url="photos/DSC03115.webp"
            setImgUrl={setImgUrl}
            setIsModalOpen={setIsModalOpen}
          />
        </div>
      </main>
    </>
  );
}
